name: CI

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version:
          - 16
        include:
          - experimental: true
            node-version: ">=17"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Install
        run: npm i
  lint:
    needs:
        - build
    strategy:
      matrix:
        node-version:
          - 16
        include:
          - experimental: true
            node-version: ">=17"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Lint
        run: npm run lint

